{% set name = "muat" %}
{% set version = "0.1.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/primasanjaya/muat/archive/refs/tags/v{{ version }}.tar.gz
  sha256: e110bd34f6c2897f3952b3c418384b9cef9b32927e9dcfa03c05749723bd5be9
build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  run_exports:
    - {{ pin_subpackage(name, max_pin="x.x") }}  # Ensures downstream compatibility

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - setuptools
    - numpy
    - pandas
    - requests
    - bedtools
    - htslib
    - natsort
    - boto3
    - openpyxl
    - scikit-learn
    - pytorch
    - pyliftover
    - bcftools
    - tqdm
    - bedops
    - swalign

test:
  imports:
    - muat

about:
  home: https://github.com/primasanjaya/muat
  license: Apache-2.0
  license_file: LICENSE
  summary: A package for Mutation Attention Tool

extra:
  recipe-maintainers:
    - primasanjaya 